name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  ci_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image (test stage)
        run: docker build --target test -t app-test .

      - name: Run test
        run: docker run app-test
